title: Lleva tu ayuda
description: Sitio para listar los centros de acopio y otra información importante para brindar ayuda en la emergencia del #VolcanDeFuego

url: llevatuayuda.guatecambia.org.gt
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Inicio
   url: /index.html
 - title: Acerca de
   url: /about
 - title: Contacto
   url: /contact

social:
   github: guatecambia
   twitter: guatecambia
   facebook: guatecambia
   email: info@guatecambia.org.gt

google_analytics: "UA-120233245-1"
